array (
  'ownerId' => NULL
  'countryCode' => 'US'
  'administrativeArea' => 'CA'
  'locality' => 'Los Angeles'
  'dependentLocality' => NULL
  'postalCode' => '92662'
  'sortingCode' => NULL
  'addressLine1' => '1234 Balboa Towers Circle'
  'addressLine2' => '#100'
  'organization' => NULL
  'organizationTaxId' => NULL
  'latitude' => NULL
  'longitude' => NULL
  'id' => 28
  'tempId' => NULL
  'draftId' => NULL
  'revisionId' => NULL
  'isProvisionalDraft' => false
  'uid' => 'c632d590-4abb-474c-9a1b-39c5559ca023'
  'siteSettingsId' => 28
  'fieldLayoutId' => NULL
  'contentId' => 17
  'enabled' => true
  'archived' => false
  'siteId' => 1
  'title' => 'Store'
  'slug' => NULL
  'uri' => NULL
  'dateCreated' => '2022-03-11T15:44:15-08:00'
  'dateUpdated' => '2022-03-14T12:44:06-07:00'
  'dateLastMerged' => NULL
  'dateDeleted' => NULL
  'trashed' => false
  'isNewForSite' => false
  'fullName' => NULL
  'firstName' => NULL
  'lastName' => NULL
  'canonicalId' => 28
  'isDraft' => false
  'isRevision' => false
  'isUnpublishedDraft' => false
  'ref' => NULL
  'status' => 'enabled'
  'structureId' => NULL
  'url' => NULL
)